##
## Makefile for MiniLibX in /home/boulon/work/c/raytraceur/minilibx
## 
## Made by Olivier Crouzet
## Login   <ol@epitech.net>
## 
## Started on  Tue Oct  5 15:56:43 2004 Olivier Crouzet
## Last update Tue May 15 15:44:41 2007 Olivier Crouzet
##

## Please use configure script


all	: do_configure

do_configure	:
	@./configure >/dev/null 2>&1 && echo "\033[32m[success]\033[0m minilibx compiled!"

clean	:
	@./configure clean >/dev/null 2>&1 && echo "\033[32m[success]\033[0m minilibx cleaned!"

re	: clean all
